### ISSUE TITLE
I want to register a case with an information object

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/gemma-documentregistratiecomponent#6]
I'm missing the model and API interface to create `ZaakInformatieObject`. When I register those, I need to supply the URL to an `EnkelvoudigInformatieObject` and the URL to a `Zaak`.

**Comment by TheophileBlard** [comment]
Forgot to add some tests for ZaakInformatieObject in DRC, will do it on Monday.
Also I'll modify the test factory, in order to assign random values inside the factory, and not during the tests (as it is currently done in the test_enkelvoudiginformatieobject.py file)
